// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lagalt_web_api.Data;

#nullable disable

namespace lagalt_web_api.Migrations
{
    [DbContext(typeof(LagaltDbContext))]
    [Migration("20230313151954_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lagalt_web_api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MotivationLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MotivationLetter = "Hallais",
                            ProjectId = 1,
                            State = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MotivationLetter = "Hallais",
                            ProjectId = 3,
                            State = 0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Contributor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.ImageUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageUrls");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Url = "https://www.youtube.com/watch?v=LkWQvzrv6gI"
                        },
                        new
                        {
                            Id = 4,
                            Url = "https://picsum.photos/200/300"
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://www.aboutmusictheory.com/wp-content/uploads/2012/04/composing-music-verse-pop-song.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://m.media-amazon.com/images/M/MV5BZmQ3MWEyNTYtOTY1OC00MTljLWI3OGUtMmU1ZDc2OTYxNDQ4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTczNjQwOTY@._V1_.jpg"
                        },
                        new
                        {
                            Id = 1,
                            Url = "https://picsum.photos/200/350,https://picsum.photos/200/250"
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.LinkerModels.ProjectImageUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ImageURLId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageURLId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectImageURLs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURLId = 1,
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageURLId = 2,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageURLId = 3,
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageURLId = 1,
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.LinkerModels.ProjectSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 2,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 3,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 1,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.LinkerModels.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            SkillId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            SkillId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            SkillId = 3,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 3,
                            Description = "Joachim Rønning",
                            GitURL = "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C6AB0EDCE8F41882EBBB782B76DD4F05D7E360D7C3F23B4F6D02C24699B26105/scale?width=1200&aspectRatio=1.78&format=jpeg",
                            Name = "Tinder v2",
                            Progress = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = 3,
                            Description = "Looking for a c# back-end developer",
                            GitURL = "https://gitlab.com/Frechr/assignment-three/-/tree/master/",
                            Name = "EF_CodeFirst",
                            Progress = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            Description = "Web app to catch pokemons!",
                            GitURL = "https://gitlab.com/JarandNL/angular_pokemontrainer",
                            Name = "Exciting_Angular_Project",
                            Progress = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "Hot youth!!!!",
                            GitURL = "https://www.imdb.com/title/tt0475293/",
                            Name = "High School Musical",
                            Progress = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Description = "Pls help make the best song ever",
                            Name = "Best song ever!!!",
                            Progress = 1
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Photoshop"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sony Vegas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fruity Loops Studio"
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portofolio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin123@admin.no",
                            FirstName = "Admin",
                            LastName = "Adminson",
                            UserStatus = false,
                            Username = "adminBoy"
                        },
                        new
                        {
                            Id = 2,
                            Email = "PerPolle@sharkboy.no,",
                            FirstName = "Per",
                            LastName = "Polle",
                            UserStatus = true,
                            Username = "sharkboy05"
                        },
                        new
                        {
                            Id = 3,
                            Email = "testing123@Proper.no",
                            FirstName = "Proper",
                            LastName = "Userito",
                            UserStatus = false,
                            Username = "ProperUser"
                        },
                        new
                        {
                            Id = 4,
                            Email = "BobBobby@mail.no",
                            FirstName = "Bob",
                            LastName = "Forr",
                            UserStatus = true,
                            Username = "StrangerHere"
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Admin", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany("Admins")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", null)
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.Application", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany("Applications")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", null)
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.Contributor", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany("Contributors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", null)
                        .WithMany("Contributors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.LinkerModels.ProjectImageUrl", b =>
                {
                    b.HasOne("lagalt_web_api.Models.ImageUrl", null)
                        .WithMany("ProjectImageUrls")
                        .HasForeignKey("ImageURLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany("ProjectImageURLs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.LinkerModels.ProjectSkill", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.Skill", null)
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.LinkerModels.UserSkill", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Skill", null)
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", null)
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.ImageUrl", b =>
                {
                    b.Navigation("ProjectImageUrls");
                });

            modelBuilder.Entity("lagalt_web_api.Models.Project", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Applications");

                    b.Navigation("Contributors");

                    b.Navigation("ProjectImageURLs");

                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("lagalt_web_api.Models.Skill", b =>
                {
                    b.Navigation("ProjectSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("lagalt_web_api.Models.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Applications");

                    b.Navigation("Contributors");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
