// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lagalt_web_api.Data;

#nullable disable

namespace lagalt_web_api.Migrations
{
    [DbContext(typeof(LagaltDbContext))]
    partial class LagaltDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdminProject", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("AdminProject");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ProjectId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ProjectId = 2
                        },
                        new
                        {
                            UserId = 3,
                            ProjectId = 3
                        },
                        new
                        {
                            UserId = 4,
                            ProjectId = 4
                        },
                        new
                        {
                            UserId = 5,
                            ProjectId = 4
                        },
                        new
                        {
                            UserId = 5,
                            ProjectId = 5
                        });
                });

            modelBuilder.Entity("ContributorProject", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ContributorProject");

                    b.HasData(
                        new
                        {
                            UserId = 5,
                            ProjectId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ProjectId = 1
                        },
                        new
                        {
                            UserId = 1,
                            ProjectId = 2
                        },
                        new
                        {
                            UserId = 2,
                            ProjectId = 3
                        },
                        new
                        {
                            UserId = 3,
                            ProjectId = 4
                        },
                        new
                        {
                            UserId = 4,
                            ProjectId = 5
                        });
                });

            modelBuilder.Entity("ImageUrlProject", b =>
                {
                    b.Property<int>("ImageUrlsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ImageUrlsId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ImageUrlProject");

                    b.HasData(
                        new
                        {
                            ImageUrlsId = 5,
                            ProjectId = 1
                        },
                        new
                        {
                            ImageUrlsId = 1,
                            ProjectId = 2
                        },
                        new
                        {
                            ImageUrlsId = 1,
                            ProjectId = 5
                        },
                        new
                        {
                            ImageUrlsId = 2,
                            ProjectId = 2
                        },
                        new
                        {
                            ImageUrlsId = 3,
                            ProjectId = 3
                        },
                        new
                        {
                            ImageUrlsId = 4,
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MotivationLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MotivationLetter = "Please give me access!",
                            ProjectId = 1,
                            State = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            MotivationLetter = "I am so good!(btw I run arch)",
                            ProjectId = 2,
                            State = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            MotivationLetter = "I am not good, but fake it til you make it!",
                            ProjectId = 2,
                            State = 0,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            MotivationLetter = "I am a fast learner, so give me a chance...",
                            ProjectId = 3,
                            State = 0,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            MotivationLetter = "This is the opportunity of a lifetime! So excited!",
                            ProjectId = 5,
                            State = 0,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.ImageUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageUrls");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Url = "https://www.youtube.com/watch?v=LkWQvzrv6gI"
                        },
                        new
                        {
                            Id = 4,
                            Url = "https://picsum.photos/200/300"
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://www.aboutmusictheory.com/wp-content/uploads/2012/04/composing-music-verse-pop-song.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://m.media-amazon.com/images/M/MV5BZmQ3MWEyNTYtOTY1OC00MTljLWI3OGUtMmU1ZDc2OTYxNDQ4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTczNjQwOTY@._V1_.jpg"
                        },
                        new
                        {
                            Id = 1,
                            Url = "https://picsum.photos/200/350,https://picsum.photos/200/250"
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 3,
                            Description = "Joachim Rønning",
                            GitURL = "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/C6AB0EDCE8F41882EBBB782B76DD4F05D7E360D7C3F23B4F6D02C24699B26105/scale?width=1200&aspectRatio=1.78&format=jpeg",
                            Name = "Tinder v2",
                            Progress = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = 3,
                            Description = "Looking for a c# back-end developer",
                            GitURL = "https://gitlab.com/Frechr/assignment-three/-/tree/master/",
                            Name = "EF_CodeFirst",
                            Progress = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            Description = "Web app to catch pokemons!",
                            GitURL = "https://gitlab.com/JarandNL/angular_pokemontrainer",
                            Name = "Exciting_Angular_Project",
                            Progress = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "Hot youth!!!!",
                            GitURL = "https://www.imdb.com/title/tt0475293/",
                            Name = "High School Musical",
                            Progress = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Description = "Pls help make the best song ever",
                            Name = "Best song ever!!!",
                            Progress = 1
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Photoshop"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sony Vegas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fruity Loops Studio"
                        });
                });

            modelBuilder.Entity("lagalt_web_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Portofolio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin123@admin.no",
                            FirstName = "Admin",
                            IsHidden = false,
                            LastName = "Adminson",
                            Username = "adminBoy"
                        },
                        new
                        {
                            Id = 2,
                            Email = "PerPolle@sharkboy.no,",
                            FirstName = "Per",
                            IsHidden = true,
                            LastName = "Polle",
                            Username = "sharkboy05"
                        },
                        new
                        {
                            Id = 3,
                            Email = "testing123@Proper.no",
                            FirstName = "Proper",
                            IsHidden = false,
                            LastName = "Userito",
                            Username = "ProperUser"
                        },
                        new
                        {
                            Id = 4,
                            Email = "BobBobby@mail.no",
                            FirstName = "Bob",
                            IsHidden = true,
                            LastName = "Forr",
                            Username = "StrangerHere"
                        },
                        new
                        {
                            Id = 5,
                            Email = "OleDole@mail.no",
                            FirstName = "Ole",
                            IsHidden = true,
                            LastName = "Dole",
                            Username = "hulken"
                        });
                });

            modelBuilder.Entity("ProjectSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectSkill");

                    b.HasData(
                        new
                        {
                            SkillId = 5,
                            ProjectId = 1
                        },
                        new
                        {
                            SkillId = 1,
                            ProjectId = 2
                        },
                        new
                        {
                            SkillId = 1,
                            ProjectId = 5
                        },
                        new
                        {
                            SkillId = 2,
                            ProjectId = 2
                        },
                        new
                        {
                            SkillId = 3,
                            ProjectId = 3
                        },
                        new
                        {
                            SkillId = 4,
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("UserSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkill");

                    b.HasData(
                        new
                        {
                            SkillId = 5,
                            UserId = 1
                        },
                        new
                        {
                            SkillId = 1,
                            UserId = 2
                        },
                        new
                        {
                            SkillId = 1,
                            UserId = 4
                        },
                        new
                        {
                            SkillId = 2,
                            UserId = 2
                        },
                        new
                        {
                            SkillId = 3,
                            UserId = 3
                        },
                        new
                        {
                            SkillId = 4,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("AdminProject", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContributorProject", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImageUrlProject", b =>
                {
                    b.HasOne("lagalt_web_api.Models.ImageUrl", null)
                        .WithMany()
                        .HasForeignKey("ImageUrlsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.Application", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectSkill", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserSkill", b =>
                {
                    b.HasOne("lagalt_web_api.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lagalt_web_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lagalt_web_api.Models.User", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
